name: FE | PR Check & Dynamic QA - Build and Deploy

on:
  # pull_request:
  #   branches:
  #     - develop # pr into develop
  #   types:
  #     - opened # pr opened
  #     - synchronize # new commit
  #     - reopened # pr reopened
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR Î≤àÌò∏ (Ïà´ÏûêÎßå ÏûÖÎ†•)'
        required: true
        type: string

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.event.inputs.pr_number }}'
  cancel-in-progress: true

env:
  # GitHub Container Registry
  IMAGE_NAME: ghcr.io/gamesung-coding/${{ github.event.repository.name }}

jobs:
  pre-comment:
    runs-on: [self-hosted, fe, qa]

    steps:
      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const message = `ÌÖåÏä§Ìä∏/QA ÏÑúÎ≤ÑÎ•º Î∞∞Ìè¨ Ï§ëÏûÖÎãàÎã§. Í∏∞Îã§Î†§Ï£ºÏÑ∏Ïöî. üòä`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });

  build-and-push:
    name: Build, Test and Push Image
    # Using self-hosted runner
    runs-on: [self-hosted, fe, qa]
    needs: pre-comment
    outputs:
      # To use next job(deploy)
      pr_number: ${{ steps.vars.outputs.pr_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Create .env file
        run: echo "${{ secrets.ENV_PR }}" > .env

      - name: Set dynamic variables
        id: vars
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "pr_number=${PR_NUMBER}" > $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gamesung-coding
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:pr-${{ steps.vars.outputs.pr_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to PR Server
    needs: build-and-push
    runs-on: [self-hosted, fe, qa]

    # Set output and secrets received through needs as global variables
    env:
      PR_NUMBER: ${{ needs.build-and-push.outputs.pr_number }}
      TEAM_USER: ${{ secrets.TEAM_USER }}
      TEAM_PASS: ${{ secrets.TEAM_PASS }}
      ENVIRONMENT_FILE: ${{ secrets.ENV_PR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          export SERVICE_NAME=fe-pr-${{ env.PR_NUMBER }}

          echo "IMAGE_TAG=${{ env.IMAGE_NAME }}:pr-${{ env.PR_NUMBER }}" >> $GITHUB_ENV
          echo "SERVICE_NAME=fe-pr-${{ env.PR_NUMBER }}" >> $GITHUB_ENV
          echo "HOST_NAME=fe-pr-${{ env.PR_NUMBER }}.${{ secrets.QA_DOMAIN }}" >> $GITHUB_ENV
          echo "DEPLOY_PATH=${{ secrets.DOCKER_DIR }}/deployments/fe-pr-${{ env.PR_NUMBER }}" >> $GITHUB_ENV

      - name: Create compose file from template
        run: |
          # Use envsubst to replace template variables with real values
          # Store result into COMPOSE_CONTENT
          export COMPOSE_CONTENT=$(envsubst < .docker/docker-compose.template.yaml)

          # Securely forward multi-linear variables to SSH with GitHub Actions masking capabilities
          echo "COMPOSE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$COMPOSE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy to server
        run: |
          set -e

          mkdir -p ${{ env.DEPLOY_PATH }}

          # write compose file from runner
          echo "[LOG] build compose file ..."
          cat <<'EOF' > ${{ env.DEPLOY_PATH }}/docker-compose.yaml
          ${{ env.COMPOSE_CONTENT }}
          EOF

          # Write application.yaml
          echo "[LOG] build application.yaml ..."
          cat <<'EOF' > ${{ env.DEPLOY_PATH }}/.env
          ${{ env.ENVIRONMENT_FILE }}
          EOF

          # change dir into deploy path
          cd ${{ env.DEPLOY_PATH }}

          # login ghcr
          echo "[LOG] log-in Github container registry"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "gamesung-coding" --password-stdin

          # pull docker image
          echo "[LOG] pull docker image"
          docker pull ${{ env.IMAGE_TAG }}

          # up docker compose
          echo "[LOG] docker container up"
          docker compose -f docker-compose.yaml -p ${{ env.SERVICE_NAME }} up -d --remove-orphans

          # prune unnecessary image
          docker image prune -f
  post-comment:
    needs:
      - build-and-push
      - deploy
    runs-on: [self-hosted, fe, qa]
    env:
      PR_NUMBER: ${{ needs.build-and-push.outputs.pr_number }}
      QA_DOMAIN: ${{ secrets.QA_DOMAIN }}
    steps:
      - name: Add PR comment
        uses: actions/github-script@v7
        with:
          script: |
            const domain = process.env.QA_DOMAIN;
            const message = `üöÄ PR ÌîÑÎ¶¨Î∑∞ ÏÑúÎ≤ÑÍ∞Ä Î∞∞Ìè¨ÎêòÏóàÏäµÎãàÎã§.\n\nurl: [Preview](https://fe-pr-${{ env.PR_NUMBER }}.${domain})`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
