name: FE | Production - Build and Deploy

on:
  # push:
  #   tags:
  #     - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-production'
  cancel-in-progress: true

env:
  # GitHub Container Registry
  IMAGE_NAME: ghcr.io/gamesung-coding/a11y-market-web
  IMAGE_TAG: ghcr.io/gamesung-coding/a11y-market-web:latest
  SERVICE_NAME: fe-production
  DEPLOY_PATH: ${{ secrets.AWS_DOCKER_DIR }}/deployments/fe-production

jobs:
  build-and-push:
    name: Build, Test and Push Image
    # Using self-hosted runner
    runs-on: [self-hosted, fe, prod]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Notify build Start
        run: echo "### Production ì„œë²„ ë¹Œë“œ ë° í…ŒìŠ¤íŠ¸ ì‹œìž‘" >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Create .env file
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gamesung-coding
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to PR Server
    needs: build-and-push
    runs-on: [self-hosted, fe, prod]

    # Set output and secrets received through needs as global variables
    env:
      DOCKER_ENV_FILE: ${{ secrets.DOCKER_ENV_PRODUCTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Deploy to server
        run: |
          mkdir -p ${{ env.DEPLOY_PATH }}

          # write compose file from runner
          echo "[LOG] copy docker-compose file ..."
          cp .docker/docker-compose.production.yaml ${{ env.DEPLOY_PATH }}/docker-compose.yaml

          # Write .env file to deploy path
          echo "[LOG] creating .env file ..."
          echo "${{ env.DOCKER_ENV_FILE }}" > "${{ env.DEPLOY_PATH }}/.env"

          # change dir into deploy path
          cd ${{ env.DEPLOY_PATH }}

          # login ghcr
          echo "[LOG] log-in Github container registry"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "gamesung-coding" --password-stdin

          # pull docker image
          echo "[LOG] pull docker image"
          docker pull ${{ env.IMAGE_TAG }}

          # up docker compose
          echo "[LOG] docker container up"
          docker compose -f docker-compose.yaml -p fe-production up -d --remove-orphans

          # prune unnecessary image
          docker image prune -f

      - name: ðŸš€ Notify Deployment Success
        if: success() # When previous step finished completely
        run: |
          echo "### âœ… Production ì„œë²„ ë°°í¬ ì„±ê³µ" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Production ì„œë²„ê°€ ì„±ê³µì ìœ¼ë¡œ ë°°í¬ë˜ì—ˆìŠµë‹ˆë‹¤." >> $GITHUB_STEP_SUMMARY
        shell: bash
